# Generated by Django 4.2.4 on 2023-11-01 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0009_job_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20, validators=[users.validators.PhoneValidator])),
                ('cv', models.URLField(blank=True, default=None, max_length=1000, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Đã nộp'), (2, 'Nhà tuyển dụng đã xem hồ sơ'), (3, 'Đã gửi lời mời phỏng vấn'), (4, 'Không được chấp nhận'), (5, 'Đã hủy')], default=1)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
