# Generated by Django 4.2.4 on 2023-11-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(1, 'Đã nộp'), (2, 'Nhà tuyển dụng đã xem hồ sơ'), (3, 'Đã gửi lời mời phỏng vấn'), (4, 'Không được chấp nhận')], default=1),
        ),
    ]
