# Generated by Django 4.2.4 on 2023-12-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
