# Generated by Django 4.2.4 on 2023-12-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created']},
        ),
    ]
