# Generated by Django 4.2.4 on 2023-09-20 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('recruiters', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('city_name', models.CharField(max_length=255)),
                ('city_code', models.PositiveSmallIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('updated', models.DateField()),
                ('expired', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recruiters.recruiterprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(1, 'Đã nộp'), (2, 'Đang xem xét'), (3, 'Đã gửi lời mời phỏng vấn'), (4, 'Không được chấp nhận'), (5, 'Thành công'), (6, 'Đã hủy')], default=1)),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candidates.candidateprofile')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.job')),
            ],
        ),
    ]
