# Generated by Django 4.2.4 on 2023-09-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary',
            new_name='salaryFrom',
        ),
        migrations.AddField(
            model_name='job',
            name='salaryTo',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
