# Generated by Django 4.2.4 on 2023-09-30 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0002_rename_salary_job_salaryfrom_job_salaryto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
