# Generated by Django 4.2.4 on 2023-09-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_recruiter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
