# Generated by Django 4.2.4 on 2023-10-16 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_updated_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='city_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
