# Generated by Django 4.2.4 on 2023-10-21 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
