# Generated by Django 4.2.4 on 2023-11-13 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_job_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-expired']},
        ),
    ]
