# Generated by Django 4.2.4 on 2023-11-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_alter_job_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
    ]
