# Generated by Django 4.2.4 on 2023-12-24 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created']},
        ),
    ]
