# Generated by Django 4.2.4 on 2023-09-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[users.validators.PhoneValidator()])),
                ('background', models.URLField()),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
