# Generated by Django 4.2.4 on 2023-09-30 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='background',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='email',
            field=models.EmailField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
