# Generated by Django 4.2.4 on 2023-11-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_alter_recruiterprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='background',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
