# Generated by Django 4.2.4 on 2023-11-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0004_recruiterprofile_background'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recruiterprofile',
            options={'ordering': ['name']},
        ),
    ]
