# Generated by Django 4.2.4 on 2023-12-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0005_alter_recruiterprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
