# Generated by Django 4.2.4 on 2023-09-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[users.validators.PhoneValidator()])),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('gender', models.IntegerField(choices=[(1, 'Nam'), (2, 'Nữ')], default=1)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
