# Generated by Django 4.2.4 on 2023-09-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidateprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Nam'), ('famele', 'Nữ')], default='male'),
        ),
    ]
