# Generated by Django 4.2.4 on 2023-11-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_tags'),
        ('candidates', '0005_alter_candidateprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='saved_jobs',
            field=models.ManyToManyField(to='jobs.job'),
        ),
    ]
