# Generated by Django 4.2.4 on 2023-12-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidateprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
