# Generated by Django 4.2.4 on 2023-12-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_job_tags'),
        ('candidates', '0007_alter_candidateprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, to='jobs.job'),
        ),
    ]
